apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: bank-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      nodeSelector:
        role: api
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - bank-api
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: bank-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: BANK_POSTGRES_HOST
              value: {{ .Values.postgresql.host | quote }}
            - name: BANK_POSTGRES_PORT
              value: {{ .Values.postgresql.service.ports.postgresql | quote }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/default.yaml
              subPath: default.yaml
      volumes:
       - name: config-volume
         configMap:
           name: {{ .Chart.Name }}-config
      